#!groovy
@Library("jenkinsLibrary@master") _

def tools = new org.devops.tools()
def build = new org.devops.build()

String workspace = "/opt/jenkins/workspace"
String srcUrl = "${env.srcUrl}"
String branchName = "${env.branchName}"
//Pipeline Start
pipeline {
    agent { node {  label "master"   
                    //customWorkspace "${workspace}"   
            }
    }

    options {
        timestamps()  //日志显示时间
        skipDefaultCheckout()  //删除隐式checkout scm语句
        //disableConcurrentBuilds() //禁止并行
        timeout(time: 1, unit: 'HOURS')  //流水线超时设置1h
    }

    stages {
        //Download Code
        stage("Download Code"){ 
            steps{  
                timeout(time:5, unit:"MINUTES"){   
                    script{ 
                        //println('Download Code')
                        tools.PrintMes('Download Code','blue')
                        checkout([$class: 'GitSCM', branches: [[name: "${branchName}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '9893232c-8de8-4c80-9168-60d1d20b7256', url: "${srcUrl}"]]])
                    }
                }
            }
        }   
    
         stage("Project Pakeges"){
            failFast true
            parallel {

                 stage("Build"){
                    steps{
                        timeout(time:20, unit:"MINUTES"){
                            script{
                                Build.Build(buildType,buildShell)

                                tools.PrintMes("Project Pakege",'green')
                               
                            }
                        }
                    }
                }
                //Scon Code
                stage("Scon Code"){
                    steps{
                        timeout(time:30, unit:"MINUTES"){
                            script{
                                //print("Scon Code")
                                tools.PrintMes("Scon Code",'green')
                            }
                        }
                    }
                }
            }
        }
    } 
       //End of construction information
    post {
        always {
            script{
                println("always")
            }
        }
        success {
            script{
                currentBuild.description = "\n Successful construction!" 
            }
        }
        failure {
            script{
                currentBuild.description = "\n Build failed!" 
            }
        }
        aborted {
            script{
                currentBuild.description = "\n Build cancel!" 
            }
        }
    }
}